heat_template_version: queens
## cli deploy
#$ openstack stack create --parameter FGT_count=2 -t cloudInit.yml demo 
# Utilisation des resourceGroup pour le deploiement des FGT
# pour update l'intra avec des FGT en +/- =>
#$ openstack stack update --wait --existing --parameter FGT_count=3 --parameter WS_count=3 demo

description: >
  Description TODO

################## PARAMETERS ##################
parameters:
  mgmt_net:
    type: string
    description: My private network
    default: "mgmt"
  public_net:
    type: string
    description: External network for floating ips
    default: "public"
  inet:
    type: string
    description: External network for floating ips
    default: "inet"
  FGT_count:
    type: number
    description: Number of FGT deployed
    default: 2
  WS_count:
    type: number
    description: Number of Web Server deployed
    default: 1
  Ingress_FGT:
    type: string
    default: "10.10.1"
  LAN_CIDR:
    type: string
    default: "10.20.1"
  Web_Server_CIDR:
    type: string
    description: CIDR for Web servers subnet
    default: "10.100.1"
  HA_CIDR:
    type: string
    description: CIDR for HA subnet
    default: "1.1.1"

################## RESOURCES ##################
resources:

# SUBNETs
  WAN:
    type: OS::Neutron::Net
    properties:
      name: "WAN"

  WAN_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "WAN_subnet"
      network_id: { get_resource: WAN }
      cidr: { list_join: [".", [{ get_param: Ingress_FGT }, "0/24"]] }
      gateway_ip: { list_join: [".", [{ get_param: Ingress_FGT}, "254"]] }
      allocation_pools:
        - start: { list_join: [".", [{ get_param: Ingress_FGT}, "3"]] }
          end: { list_join: [".", [{ get_param: Ingress_FGT}, "250"]] }

  LAN:
    type: OS::Neutron::Net
    properties:
      name: "LAN"

  LAN_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "LAN_subnet"
      network_id: { get_resource: LAN }
      cidr: { list_join: [".", [{ get_param: LAN_CIDR }, "0/24"]] }
      gateway_ip: null
      allocation_pools:
        - start: { list_join: [".", [{ get_param: LAN_CIDR}, "3"]] }
          end: { list_join: [".", [{ get_param: LAN_CIDR}, "250"]] }

  net01:
    type: OS::Neutron::Net
    properties:
      name: "NET_01"

  net01_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "NET01_subnet"
      network_id: { get_resource: net01 }
      cidr: { list_join: [".", [{ get_param: Web_Server_CIDR }, "0/24"]] }
      gateway_ip: 10.100.1.254
      allocation_pools:
        - start: { list_join: [".", [{ get_param: Web_Server_CIDR}, "3"]] }
          end: { list_join: [".", [{ get_param: Web_Server_CIDR}, "250"]] }

  net_ha:
    type: OS::Neutron::Net
    properties:
      name: "net_ha"

  ha_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "HA_subnet"
      network_id: { get_resource: net_ha }
      cidr: { list_join: [".", [{ get_param: HA_CIDR }, "0/24"]] }
      gateway_ip: null
      enable_dhcp: false

# INSTANCES

# FGT WAN HA mode
  FGT_WAN:
    type: instance.yaml
    properties:
      image: "fgt604"
      flavor: "m1.amphora"
      net_id_list:
        - { get_resource: WAN }
        - { get_param: inet }
      hostname: "FGT_WAN"
      config: { get_file: ./config/fgt.conf }

# FGT LAN HA mode
  FGT_LAN:
    type: instance.yaml
    properties:
      image: "fgt604"
      flavor: "m1.amphora"
      net_id_list:
        - { get_resource: LAN }
        - { get_resource: net01 }
      hostname: "FGT_LAN"
      config: { get_file: ./config/fgt.conf }

# FGT ResourceGroup
  FGTs:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: FGT_count }
      resource_def:
        # .yml not supported ! .yaml or .template
        type: instance.yaml
        properties:
          image: "fgt604"
          flavor: "m1.amphora"
          net_id_list:
            - { get_resource: WAN }
            - { get_resource: LAN }
            - { get_resource: net_ha }
          hostname: "FGT_%index%"
          config: { get_file: ./config/fgt.conf }

# UBUNTU ResourceGroup
  Web_Servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: WS_count }
      resource_def:
        type: instance.yaml
        properties:
          image: "ubuntu_16.04"
          flavor: "ds1G"
          net_id_list: [{ get_resource: net01 }]
          hostname: "Web_server_%index%"
          config: { get_file: ./config/ubuntu.conf }

################## OUTPUTS ##################
outputs:
  FGT_WAN:
    value: ["FGT_WAN", { get_attr: [FGT_WAN, FloatingIP] }]
  FGT_LAN:
    value: ["FGT_LAN", { get_attr: [FGT_LAN, FloatingIP] }]
  FGTs:
    value: 
      repeat:
        template:
          [<%hostname%>, <%IP%>]
        for_each:
          <%IP%>: { get_attr: [FGTs, FloatingIP]}
          <%hostname%>: { get_attr: [FGTs, Hostname] }
        permutations: false
  Web_Servers:
    value:
      repeat:
        template:
          [<%hostname%>, <%IP%>]
        for_each:
          <%IP%>: { get_attr: [Web_Servers, FloatingIP]}
          <%hostname%>: { get_attr: [Web_Servers, Hostname] }
        permutations: false
