- hosts: localhost
#  strategy: debug
  vars:
   host: "172.24.4.14"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Set static route on the fortigate
    fortiosconfig:
     action: "set"
     host:  "{{  host }}"
     username: "{{ username}}"
     password: "{{ password }}"
     vdom:  "{{  vdom }}"
     config: "router static"
     config_parameters:
       seq-num: "8"
       dst: "1.1.1.1 255.255.255.255"
       device: "port1"
       gateway: "198.27.111.190"
