---
- hosts: localhost
  vars:
    host: "172.24.4.14"
    username: "User1"
    password: "fortinet"
    vdom: "root"
  tasks:
    - name: Get informations
      fortiosconfig:
        config: "system global"
        action: "get"
        host:  "{{ host }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          name: "global"

