---
- hosts: localhost
  vars:
    username: "User1"
    password: "fortinet"
    vdom: "root"
  tasks:
    - name: Include IP of FGT in var 'FGT_IP'
      include_vars:
        file: fortigate_IP.yaml
        name: FGT
    # - name: Include licenses filename of var 'licenses'
    #   include_vars:
    #     file: licenses.yaml
    #     name: licenses
    # - name: Upload licenses
    #   fortiosconfig:
    #     config: "system vmlicense upload"
    #     action: "upload"
    #     host: "{{ item.0 }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     vdom:  "global"
    #     https: False
    #     config_parameters:
    #       filename: "{{ item.1 }}"
    #   with_together:
    #     - "{{ FGT.IP }}"
    #     - "{{ licenses.licenses }}"
    #   when: item.0 != None
    - name: Get system informations
      fortiosconfig:
        config: "system global"
        action: "get"
        host:  "{{ item }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          name: "global"
      loop: "{{ FGT.IP }}"
      # - name: create firewall policy
      #   fortiosconfig:
      #     config: "firewall policy"
      #     action: "set"
      #     host: "{{ host }}"
      #     username: "{{ username }}"
      #     password: "{{ password }}"
      #     vdom: "{{ vdom }}"
      #     https: False
      #     config_parameters:
      #       policyid: "1"
      #       name: "WAN to LAN"
      #       action: "accept"
      #       srcintf: [ {"name": "DOWN"} ]
      #       dstintf: [{"name":"UP"} ]
      #       srcaddr: [{"name":"all"} ]
      #       dstaddr: [{"name":"all"}]
      #       schedule: "always"
      #       service: [{"name":"ALL"}]
      #       fsso: "disable"
      #       nat: "enable"
      # loop: "{{ FGT.IP }}"
