---
- hosts: localhost
  vars:
    username: "User1"
    password: "fortinet"
    vdom: "root"
  tasks:
    - name: Include IP of FGT in var 'FGT'
      include_vars:
        file: fortigate_IP.yaml
        name: FGT
    # - name: Include licenses filename of var 'licenses'
    #   include_vars:
    #     file: licenses.yaml
    #     name: licenses
    # - name: Upload licenses
    #   fortiosconfig:
    #     config: "system vmlicense upload"
    #     action: "upload"
    #     host: "{{ FGT.IP.LAN.0 }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     vdom:  "global"
    #     https: False
    #     config_parameters:
    #       filename: "{{ FGT.IP.LAN.1 }}"
    #   with_together:
    #     - "{{ FGT.IP.LAN }}"
    #     - "{{ licenses.licenses }}"
    #   when: FGT.IP.LAN.0 != None

    # - name: Get system informations
    #   fortiosconfig:
    #     config: "system global"
    #     action: "get"
    #     host:  "{{ FGT.IP.LAN }}"  
    #     username: "{{ username }}"  
    #     password: "{{ password }}"
    #     vdom: "global"
    #     https: False
    #     config_parameters:
    #       name: "global"

    - name: Set interface port 2
      fortiosconfig:
        config: "system interface"
        action: "set"
        host:  "{{ FGT.IP.LAN }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          name: "port2"
          vdom: "root"
          allowaccess: 'ping'
          type: "physical"
          defaultgw: "disable"
          bfd: "enable"

    - name: Set interface port 3
      fortiosconfig:
        config: "system interface"
        action: "set"
        host:  "{{ FGT.IP.LAN }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          name: "port3"
          vdom: "root"
          mode: static
          ip: "10.100.1.254 255.255.255.0"
          allowaccess: 'ping'
          type: "physical"
          snmp-index: "3"
          defaultgw: "disable"
          mtu-override: "enable"
          mtu: "1450"

    - name: Set inpection mode flow
      fortiosconfig:
        config: "system settings"
        action: "set"
        host:  "{{ FGT.IP.LAN }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          inspection-mode: "flow"
          gui-allow-unnamed-policy: "enable"
          bfd: "enable"
          bfd-desired-min-tx: "10"
          bfd-required-min-rx: "10"
          asymroute: "enable"

    - name: Create system zone MGMT
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "MGMT"

    - name: Create system zone DOWN
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "DOWN"
    - name: Create system zone UP
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "UP"
    - name: Set interface zones
      fortiosconfig:
        action: "ssh"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        commands: |
          config system zone
            edit MGMT
              set interface port1
            next
            edit DOWN
              set interface port3
            next
            edit UP
              set interface port2
            next
          end

    - name: Config OSPF
      fortiosconfig:
        action: "ssh"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        commands: |
          config router ospf
              set router-id 10.199.99.201
              config area
                  edit 0.0.0.0
                  next
              end
              config ospf-interface
                  edit "UP"
                      set interface "port2"
                      set dead-interval 40
                      set hello-interval 10
                      set bfd enable
                  next
                  edit "DOWN"
                      set interface "port3"
                      set dead-interval 40
                      set hello-interval 10
                  next
              end
              config network
                  edit 1
                      set prefix 10.20.1.0 255.255.255.0
                  next
                  edit 2
                      set prefix 10.100.1.0 255.255.255.0
                  next
              end
          end

    - name: create firewall policy 1
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "1"
          name: "DOWN to UP"
          action: "accept"
          srcintf: [{"name": "DOWN"}]
          dstintf: [{"name":"UP"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"

    - name: create firewall policy 2
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "2"
          name: "UP to DOWN"
          action: "accept"
          srcintf: [{"name": "UP"}]
          dstintf: [{"name":"DOWN"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"

    - name: create firewall policy 3
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "3"
          action: "accept"
          srcintf: [{"name": "MGMT"}]
          dstintf: [{"name":"UP"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"

    - name: create firewall policy 4
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "4"
          action: "accept"
          srcintf: [{"name": "UP"}]
          dstintf: [{"name":"MGMT"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"

    - name: Set static route
      fortiosconfig:
        config: "router static"
        action: "set"
        host: "{{ FGT.IP.LAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          seq-num: "1"
          gateway: "192.168.99.1"
          dst: "100.66.199.0 255.255.255.0"
          device: "port1"
