---
- hosts: localhost
  vars:
    username: "User1"
    password: "fortinet"
    vdom: "root"
    HA_IP_list: []
  tasks:
    - name: Include IP of FGT in var 'FGT'
      include_vars:
        file: fortigate_IP.yaml
        name: FGT
    # - name: Include licenses filename of var 'licenses'
    #   include_vars:
    #     file: licenses.yaml
    #     name: licenses
    # - name: Upload licenses
    #   fortiosconfig:
    #     config: "system vmlicense upload"
    #     action: "upload"
    #     host: "{{ item.0 }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     vdom:  "global"
    #     https: False
    #     config_parameters:
    #       filename: "{{ item.1 }}"
    #   with_together:
    #     - "{{ item }}"
    #     - "{{ licenses.licenses }}"
    #   when: item.0 != None
    - name: Get system informations
      fortiosconfig:
        config: "system global"
        action: "get"
        host:  "{{ item }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          name: "global"
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: Set interface port 4
      fortiosconfig:
        config: "system interface"
        action: "set"
        host:  "{{ item }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          name: "port4"
          vdom: "root"
          alias: "HA"
          mode: static
          ip: "{{ FGT.CIDR.HA }}.{{ index + 1 }} 255.255.255.0"
          type: "physical"
          snmp-index: "4"
          defaultgw: "disable"
          mtu-override: "enable"
          mtu: "1450"
      loop: "{{ FGT.IP.FGTs_HA }}"
      loop_control:
        index_var: index

    - name: Set HA port
      fortiosconfig:
        config: "system ha"
        action: "set"
        host:  "{{ item }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        https: False
        config_parameters:
          hbdev: "port4 100"
          session-pickup: "enable"
          session-pickup-connectionless: "enable"
          session-pickup-expectation: "enable"
          override: "disable"
          priority: "{{ index }}00"
      loop: "{{ FGT.IP.FGTs_HA }}"
      loop_control:
        index_var: index

    # - name: Set cluster
    #   fortiosconfig:
    #     config: "system cluster-sync"
    #     action: "set"
    #     host:  "{{ item[0] }}"  
    #     username: "{{ username }}"  
    #     password: "{{ password }}"
    #     https: False
    #     config_parameters:

    #       peerip: "{{ FGT.CIDR.HA }}.{{ item[1] }}"
    #       syncvd: "root"
    #   with_nested:
    #     - "{{ FGT.IP.FGTs_HA }}"
    #     - [ "1", "2", "3", "4", "5"]

    - name: Set cluster
      fortiosconfig:
        action: "ssh"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        commands: |
          config system cluster-sync
            edit 1
              set peerip 1.1.1.1
              set syncvd "root"
            next
            edit 2
              set peerip 1.1.1.2
              set syncvd "root"
            next
          end
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: Create system zone MGMT
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "MGMT"
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: Create system zone LAN
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "LAN"
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: Create system zone WAN
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "WAN"
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: Set interface zones
      fortiosconfig:
        action: "ssh"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        commands: |
          config system zone
            edit MGMT
              set interface port1
            next
            edit WAN
              set interface port2
            next
            edit LAN
              set interface port3
            next
          end
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: create firewall policy 1
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "1"
          name: "LAN to WAN"
          action: "accept"
          srcintf: [{"name": "LAN"}]
          dstintf: [{"name":"WAN"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: create firewall policy 2
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "2"
          name: "WAN to LAN"
          action: "accept"
          srcintf: [{"name": "WAN"}]
          dstintf: [{"name":"LAN"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"
      loop: "{{ FGT.IP.FGTs_HA }}"

    - name: Set static route
      fortiosconfig:
        config: "router static"
        action: "set"
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          seq-num: "1"
          gateway: "192.168.99.1"
          dst: "100.66.199.0 255.255.255.0"
          device: "port1"
      loop: "{{ FGT.IP.FGTs_HA }}"
