---
- hosts: localhost
  vars:
    username: "User1"
    password: "fortinet"
    vdom: "root"
  tasks:
    - name: Include IP of FGT in var 'FGT'
      include_vars:
        file: fortigate_IP.yaml
        name: FGT

    # - name: Include licenses filename of var 'licenses'
    #   include_vars:
    #     file: licenses.yaml
    #     name: licenses
    # - name: Upload licenses
    #   fortiosconfig:
    #     config: "system vmlicense upload"
    #     action: "upload"
    #     host: "{{ FGT.IP.WAN.0 }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     vdom:  "global"
    #     https: False
    #     config_parameters:
    #       filename: "{{ FGT.IP.WAN.1 }}"
    #   with_together:
    #     - "{{ FGT.IP.WAN }}"
    #     - "{{ licenses.licenses }}"
    #   when: FGT.IP.WAN.0 != None

    - name: Set interface inet (port3)
      fortiosconfig:
        config: "system interface"
        action: "set"
        host:  "{{ FGT.IP.WAN }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          name: "port3"
          mode: "static"
          ip: "10.0.1.101 255.255.255.0"
          allowaccess: "ping"
          type: "physical"
          snmp-index: "2"
          bfd: "enable"
          defaultgw: "disable"
          mtu-override: "enable"
          mtu: "1450"

    - name: Set inpection mode flow
      fortiosconfig:
        config: "system settings"
        action: "set"
        host:  "{{ FGT.IP.WAN }}"  
        username: "{{ username }}"  
        password: "{{ password }}"
        vdom: "global"
        https: False
        config_parameters:
          inspection-mode: "flow"
          gui-allow-unnamed-policy: "enable"
          bfd: "enable"
          bfd-desired-min-tx: "10"
          bfd-required-min-rx: "10"
          asymroute: "enable"

    - name: Create system zone MGMT
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "MGMT"
    - name: Create system zone DOWN
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "DOWN"
    - name: Create system zone UP
      fortiosconfig:
        config: "system zone"
        action: "set"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          name: "UP"
    - name: Set interface zones
      fortiosconfig:
        action: "ssh"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        commands: |
          config system zone
            edit MGMT
              set interface port1
            next
            edit DOWN
              set interface port3
            next
            edit UP
              set interface port2
            next
          end

    - name: Config OSPF
      fortiosconfig:
        action: "ssh"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        commands: |
          config router ospf
            set default-information-originate always
            set router-id 10.199.99.101
            config area
              edit 0.0.0.0
              next
            end
            config ospf-interface
              edit "DOWN"
                set interface "port2"
                set dead-interval 40
                set hello-interval 10
                set bfd enable
              next
            end
            config network
              edit 1
                set prefix 10.10.1.0 255.255.255.0
              next
              edit 2
                set prefix 10.0.1.0 255.255.255.0
              next
            end
          end

    - name: create firewall policy 1
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "1"
          name: "WAN to LAN"
          action: "accept"
          srcintf: [{"name": "DOWN"}]
          dstintf: [{"name":"UP"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"

    - name: create firewall policy 2
      fortiosconfig:
        config: "firewall policy"
        action: "set"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          policyid: "2"
          name: "LAN to WAN"
          action: "accept"
          srcintf: [{"name": "UP"}]
          dstintf: [{"name":"DOWN"}]
          srcaddr: [{"name":"all"}]
          dstaddr: [{"name":"all"}]
          schedule: "always"
          service: [{"name":"ALL"}]
          fsso: "disable"

    - name: Set static route WAN
      fortiosconfig:
        config: "router static"
        action: "set"
        host: "{{ FGT.IP.WAN }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        https: False
        config_parameters:
          seq-num: "1"
          gateway: "10.0.1.1"
          distance: "110"
          priority: "20"
          device: "port3"
